import { Shoe, Event, Trail } from './types';

export const INVENTORY: Shoe[] = [
  {
    id: '1',
    name: 'Glycerin 22',
    brand: 'Brooks',
    price: 160,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Maximal',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    description: 'The ultimate in softness. Nitrogen-infused DNA LOFT v3 offers supreme comfort for long road miles.',
    staffPick: true,
  },
  {
    id: '2',
    name: 'Clifton 10',
    brand: 'Hoka',
    price: 145,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Balanced',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop',
    description: 'Lighter and more cushioned than ever. The daily driver that changed the perception of what a running shoe could be.',
  },
  {
    id: '3',
    name: 'Peregrine 15',
    brand: 'Saucony',
    price: 140,
    category: 'Trail',
    stability: 'Neutral',
    cushion: 'Firm',
    widthOptions: ['Standard'],
    image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400&h=300&fit=crop',
    description: 'Named after the fastest bird on Earth. Grippy PWRTRAC rubber dominates the mud and dirt.',
    staffPick: true,
  },
  {
    id: '4',
    name: 'Adrenaline GTS 23',
    brand: 'Brooks',
    price: 140,
    category: 'Road',
    stability: 'Stability',
    cushion: 'Balanced',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=300&fit=crop',
    description: 'Known as the "Go-To Shoe". GuideRails support keeps excess movement in check.',
  },
  {
    id: '5',
    name: 'Speedgoat 6',
    brand: 'Hoka',
    price: 155,
    category: 'Trail',
    stability: 'Neutral',
    cushion: 'Maximal',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=300&fit=crop',
    description: 'A workhorse designed for technical trails. Vibram Megagrip lug patterns ensure you stay vertical.',
  },
  {
    id: '6',
    name: 'Pegasus Trail 5',
    brand: 'Nike',
    price: 140,
    category: 'Hybrid',
    stability: 'Neutral',
    cushion: 'Balanced',
    widthOptions: ['Standard'],
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=300&fit=crop',
    description: 'Seamlessly transitions from paved roads to dirt paths. React foam provides a smooth ride anywhere.',
  },
  {
    id: '7',
    name: 'Paradigm 7',
    brand: 'Altra',
    price: 170,
    category: 'Road',
    stability: 'Stability',
    cushion: 'Maximal',
    widthOptions: ['Wide'],
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400&h=300&fit=crop',
    description: 'Zero drop with maximum cushion and guidance. Features the signature FootShape toe box.',
  },
  {
    id: '8',
    name: 'Kayano 30',
    brand: 'Asics',
    price: 160,
    category: 'Road',
    stability: 'Stability',
    cushion: 'Maximal',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=400&h=300&fit=crop',
    description: 'Revolutionary 4D GUIDANCE SYSTEM provides adaptive stability for overpronators.',
  },
  {
    id: '9',
    name: 'Endorphin Speed 4',
    brand: 'Saucony',
    price: 170,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Firm',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=300&fit=crop',
    description: 'Carbon-fiber plate propels you forward with each stride. Built for tempo runs and race day.',
    staffPick: true,
  },
  {
    id: '10',
    name: 'Vaporfly 3',
    brand: 'Nike',
    price: 250,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Firm',
    widthOptions: ['Standard'],
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=300&fit=crop',
    description: 'The pinnacle of racing innovation. ZoomX foam and carbon plate deliver world-record performance.',
  },
  {
    id: '11',
    name: 'Lone Peak 8',
    brand: 'Altra',
    price: 145,
    category: 'Trail',
    stability: 'Neutral',
    cushion: 'Balanced',
    widthOptions: ['Wide'],
    image: 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=400&h=300&fit=crop',
    description: 'The most popular trail shoe in America. Zero drop meets grippy MaxTrac outsole for natural trail running.',
  },
  {
    id: '12',
    name: 'Fresh Foam X 1080v13',
    brand: 'New Balance',
    price: 165,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Maximal',
    widthOptions: ['Standard', 'Wide', 'Extra Wide'],
    image: 'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=400&h=300&fit=crop',
    description: 'Plush Fresh Foam X midsole delivers soft, smooth transitions. Perfect for easy days and long runs.',
  },
  {
    id: '13',
    name: 'Triumph 22',
    brand: 'Saucony',
    price: 160,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Maximal',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400&h=300&fit=crop',
    description: 'Maximum cushioning without the weight. PWRRUN+ foam creates a luxurious ride for daily training.',
  },
  {
    id: '14',
    name: 'Challenger 9',
    brand: 'Hoka',
    price: 145,
    category: 'Hybrid',
    stability: 'Neutral',
    cushion: 'Balanced',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1739132268693-8ba353f0959c?w=400&h=300&fit=crop',
    description: 'The original trail-to-road crossover. Updated with lighter foam and grippier lugs.',
  },
  {
    id: '15',
    name: 'Ghost 16',
    brand: 'Brooks',
    price: 140,
    category: 'Road',
    stability: 'Neutral',
    cushion: 'Balanced',
    widthOptions: ['Standard', 'Wide'],
    image: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?w=400&h=300&fit=crop',
    description: 'The perfect blend of cushion and responsiveness. DNA LOFT v2 foam makes every run feel effortless.',
    staffPick: true,
  },
];

export const EVENTS: Event[] = [
  { id: '1', title: 'Sole Train Running Club', day: 'Tuesday', time: '6:30 PM', location: 'Store (122 Public Sq)', type: 'Club Run' },
  { id: '2', title: 'Sole Train Running Club', day: 'Thursday', time: '6:30 PM', location: 'Store (122 Public Sq)', type: 'Club Run' },
  { id: '3', title: 'Saturday Morning Miles', day: 'Saturday', time: '8:00 AM', location: 'Store (122 Public Sq)', type: 'Club Run' },
  { id: '4', title: 'Trail Heads', day: 'Monday', time: '6:30 PM', location: 'Various Locations', type: 'Trail Run' },
  { id: '5', title: 'Wednesday Recovery Run', day: 'Wednesday', time: '6:00 AM', location: 'Store (122 Public Sq)', type: 'Club Run' },
  { id: '6', title: 'Sunday Long Run', day: 'Sunday', time: '7:30 AM', location: 'Chippewa Rail Trail', type: 'Long Run' },
  { id: '7', title: 'Track Tuesday', day: 'Tuesday', time: '5:30 PM', location: 'Medina High School Track', type: 'Speed Work' },
  { id: '8', title: 'Trail Heads - Night Edition', day: 'Friday', time: '7:00 PM', location: 'Hubbard Valley', type: 'Trail Run' },
  { id: '9', title: 'Coffee & Kilometers', day: 'Saturday', time: '9:30 AM', location: 'Store (122 Public Sq)', type: 'Social Run' },
  { id: '10', title: 'Tempo Thursday', day: 'Thursday', time: '5:45 AM', location: 'Store (122 Public Sq)', type: 'Speed Work' },
];

export const TRAILS: Trail[] = [
  { id: '1', name: 'Austin Badger Park', type: 'Trails', distance: '3-5 miles', image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=100&h=100&fit=crop' },
  { id: '2', name: 'Chippewa Rail Trail', type: 'Paved', distance: '12 miles', image: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=100&h=100&fit=crop' },
  { id: '3', name: 'Hubbard Valley', type: 'Mixed', distance: '2.5 miles', image: 'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=100&h=100&fit=crop' },
  { id: '4', name: 'Lake Medina', type: 'Trails', distance: '2 miles', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=100&h=100&fit=crop' },
  { id: '5', name: 'Buckeye Woods Park', type: 'Trails', distance: '4 miles', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=100&h=100&fit=crop' },
  { id: '6', name: 'Alderfer-Chatfield Park', type: 'Mixed', distance: '3 miles', image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=100&h=100&fit=crop' },
  { id: '7', name: 'River Styx Park', type: 'Trails', distance: '1.5 miles', image: 'https://images.unsplash.com/photo-1542359649-31e03cd4d909?w=100&h=100&fit=crop' },
  { id: '8', name: 'Princess Ledges', type: 'Trails', distance: '2 miles', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=100&h=100&fit=crop' },
  { id: '9', name: 'Hinckley Reservation', type: 'Mixed', distance: '6-10 miles', image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=100&h=100&fit=crop' },
  { id: '10', name: 'Cuyahoga Valley Towpath', type: 'Paved', distance: '20 miles', image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=100&h=100&fit=crop' },
];

export const STORE_INFO = {
  address: '122 Public Square, Medina, OH',
  phone: '(330) 723-7653',
  hours: [
    'Mon-Fri: 10am - 7pm',
    'Sat: 10am - 6pm',
    'Sun: 12pm - 5pm'
  ]
};